language: python

python:
  - "3.4"
  - "2.7"

branches:
  only:
    - master

# command to install requirements
install:
  - python setup.py -q install
  - pip install nosetests

# command to run tests, e.g. python setup.py test
script:
  - nosetests

after_success:
  coveralls
